### ISSUE TITLE
Works improperly with Ubuntu Gnome 14.10！

### ISSUE THREAD

**Issue by amitbha** [wilfm/GnomeExtensionMaximusTwo#1]
Sometimes MaximusTwo stucks the poping-up window of some applictions. For example, when I try to open the gnome-control-center, the mouse-cursor turns into a cross weirdly, and the window of control center never shows up untill press the left mouse button.
After turn off MaximusTwo, everything is fine.

**Comment by Hernou** [comment]
I have the same like proble (ubuntu-gnome 14.10/3.14.3)
I want see properties of very anything (in gimp, nautilus, banshee, realy anithing), my cursor is changer by a cross, and I must click on some I want to see properties to open the properties windows...

**Comment by wilfm** [comment]
May have been fixed with version using update from Pixel Saver (https://github.com/deadalnix/pixel-saver/issues/14), you can get it here: https://github.com/wilfm/GnomeExtensionMaximusTwo/releases/tag/4
