### ISSUE TITLE
Not working with themes other than Adwaita

### ISSUE THREAD

**Issue by hee502** [wilfm/GnomeExtensionMaximusTwo#10]
The extension stops working if the any theme other than default (Adwaita) is used. As a long-time Ambiance theme user, I would appreciate if you could fix the issue.

**Comment by wilfm** [comment]
Yeah this is a bug in the - as shown in the [decoration.js](https://github.com/wilfm/GnomeExtensionMaximusTwo/blob/master/maximus-two-wilfinitlike.gmail.com/decoration.js#L77-92)

I have created a version of Ambiance's metacity theme based on Zukitwo's, I will upload it (when I work out how other than a link to dropbox). If you also want the Gnome Shell to match, [this theme](http://gnome-look.org/content/show.php/Ambiance-Gnome?content=166632) may work for you. Screenshots:
![screenshot from 2015-02-02 18 14 06](https://cloud.githubusercontent.com/assets/6739839/6006071/65ff598a-ab07-11e4-92a8-3fb1937f6cfe.png)
![screenshot from 2015-02-02 18 12 36](https://cloud.githubusercontent.com/assets/6739839/6006072/6602186e-ab07-11e4-9acb-f2fbb9c36c80.png)
