### ISSUE TITLE
Not working with WINE

### ISSUE THREAD

**Issue by justcomplaining** [wilfm/GnomeExtensionMaximusTwo#11]
Ubuntu 14.04

WINE windows title bars are not hidden...

**Comment by DoctorJellyface** [comment]
Just a heads-up: this bug is in ubuntu with Compiz too, you have to use `compizconfig-settings-manager` to set a rule to remove the titlebar on all windows when they are maximized. It's probably the same here.

**Comment by justcomplaining** [comment]
WINE 1.7.19
gnome-shell 3.10.4
App: League of Legends (Game) but the same problems with the wineconfig window and the emulated desktop, if one uses it.
Window manager is handling the decorations.

**Comment by wilfm** [comment]
Could you add a screenshot please?

**Comment by wilfm** [comment]
It works well on many apps on Gnome 3.14 and Wine 1.7.47 (Fedora 21 x64):

[ ![screenshot from 2015-08-05 18 53 27](https://cloud.githubusercontent.com/assets/6739839/9093401/d9ff5e3e-3ba3-11e5-977c-8936137548e5.png) ](https://cloud.githubusercontent.com/assets/6739839/9093401/d9ff5e3e-3ba3-11e5-977c-8936137548e5.png)

You need the window manager to control and decorate the Windows to make it work:
![screenshot from 2015-08-05 18 56 29](https://cloud.githubusercontent.com/assets/6739839/9093411/ea5082e0-3ba3-11e5-882d-6ed50222b958.png)
