### ISSUE TITLE
Sotime appear a black line on top

### ISSUE THREAD

**Issue by dmarrazzo** [wilfm/GnomeExtensionMaximusTwo#12]
it's like the notification area grows to fill the gap of the title bar. Clicking on the notification area solves, but it's annoying.

**Comment by ioqzc** [comment]
I can confirm it is happening on Fedora 21 Workspace(Gnome 3.14 on my Dell laptop) with the following notes: Sometimes the "black line on the top" (actually it seems to be the space that would be occupied by the title bar) is not black, but transparent(I can see my desktop background through that space). I can reproduce this systematically in some diffent configurations and only sometimes in others. For example, to reproduce thissystematically: lock and unlock the screen after doing a workspace switch, like this:
1. Go to the second Workspace: "Ctrl+Alt+Down"
2. Open a new terminal window and maximize it: "Super" and write 'terminal' and "Enter" to open it; then "Alt+Space" to open the window drop-down menu, "Down" to select the Maximize option and "Enter" to choose it.
3. Notice the title bar of the terminal window is not there, as expected; Switch back to the first workspace and forward to the second: "Ctl+Alt+Up" and "Ctl+Alt+Down".
4. Lock the screen: "Super+L"
5. Unlock the screen: "Enter" and write your password...
6. Notice that now there is a transparent or, sometimes, black line on the top of the terminal window, with the apparent size and shape of the would-be title bar; also, if I am fast enough I can actually see the title bar in before it gets 'deleted' into transparency/blackness... that was unexpected.
7. Workarounds: 
7.1. Unmaximize & maximize the window by any method: drag and drop holding the  menu bar or use the "Alt+Space" window menu. 
7.2. Just click the gnome top pannel(the empty area).

**Comment by wilfm** [comment]
I know this issue in Fedora 21 (my current primary OS), and that it occurs with xorg-x11-utils installed. In Gnome transparency in Windows often appears as the window behind it (most of the time frozen) or a black region. I mainly have this problem with apps in Wine start screens etc.
@dmarrazzo as for panel/notification area 'growing', I think this looks like this because the default shell theme is black so matches the void where the titlebar was. Using another theme such as [Zukitwo](http://lassekongo83.deviantart.com/art/Zukitwo-203936861), the area stills appears black/'transparent'.
I suspect this is mis-coordination between the extension and window manager (or something else)

This issue is similar to #2 and #13.

N.B. a quick fix for Firefox is to press <kbd>Alt</kbd> twice, as that makes the the menubar show and hide.removing the gap.

**Comment by Distopico** [comment]
I have the same problem, when lock the screen and unlock appear black line in the top in same place of windows controls, my OS y Parabola GNU/Linux (ArchLinux based) gnome 3.14.2

**Comment by emerinohdz** [comment]
Same problem here, archlinux gnome shell 3.14.3, but it's been like this since 3.12.

**Comment by wilfm** [comment]
Same issue as in #18 . Sorry about the delay of getting it fixed, but I suspect it may have something to do with the X utils and the new versions of Gnome. Once I have set up a 'test rig' to fully debug this, I should be able to fix this.

**Comment by elmeunick9** [comment]
Notice that when using the option in the theme it works fine: http://www.webupd8.org/2011/05/how-to-remove-maximized-windows.html

**Comment by Distopico** [comment]
The merge request [pull/22](https://github.com/wilfm/GnomeExtensionMaximusTwo/pull/22)  fix this issues in gnome 3.16 Parabola GNU/Linux

**Comment by dffischer** [comment]
For me, #22 does not fix this on Arch Linux with gnome-shell 3.16. I can confirm @emerinohdz that it occurs since 3.12.

**Comment by aquatix** [comment]
Here, #22 does not eliminate the black bar either. On 3.14, the current pixel-saver extension version worked better where MaximusTwo already showed the black bar. That extension now doesn't want to work anymore, but maybe you can work together to search for a solution?

**Comment by wilfm** [comment]
@aquatix - pixel saver basically what this extension is - the window button part of it didn't seem to work so I cut it out to get the titlebar removing functionality. I'm sure the person that wrote it going to update it for 3.12+ - on [this page](https://github.com/deadalnix/pixel-saver) it says  `Version 1.3 will be the last version to support gnome shell prior to 3.12 .`. I have tried including the windows buttons functionality in this extension, and got a rather buggy result - my current thinking for that is that I could attempt a update of the [Window Buttons](https://extensions.gnome.org/extension/426/window-buttons/) extension from which I think it draws the buttons' functionality

**Comment by aquatix** [comment]
@wilfm ah interesting; I don't really care for the window buttons (it's buggy too with multiple monitors somehow; always unsure what window you're about to close), but somehow in the few months I used pixelsaver with Gnome 3.14 (!) it never showed the black bar, while both Maximus and MaximusTwo somehow do.

**Comment by wilfm** [comment]
@aquatix - thats more interesting... it seems to have been updated since I last looked at it, so thats probably why :D I'll have look and see if I can implement any updates that fixed stuff

**Comment by aquatix** [comment]
Cool :) That would totally rock!

**Comment by wilfm** [comment]
Updates *should* fix this for 99.999981% of the time.... comment if it doesn't :)

**Comment by xHN35RQ** [comment]
Still seeing this occasionally on Gnome 3 GTK 3.14
