### ISSUE TITLE
Konsole doesn't fullscreen after screen lock

### ISSUE THREAD

**Issue by sethwoodworth** [wilfm/GnomeExtensionMaximusTwo#13]
Steps to reproduce:

1. Open Konsole in gnome-shell.  
2. Fullscreen it with Meta+<up>
3. Lock screen with Meta+L (or wait for screen to time out/suspend)
4. Wakeup machine

behavior: Konsole is full-screened, except where the title bar _would_ be shows desktop
![konsole-not-fullscreen](https://cloud.githubusercontent.com/assets/123998/5428192/ba2acb2c-8387-11e4-858c-9a146132ab9a.png)

Expected behaviour: Konsole will stay full-screened
![konsole-fullscreen](https://cloud.githubusercontent.com/assets/123998/5428193/ba2b5646-8387-11e4-971a-9bb38d7dd4cf.png)

Gnome Shell Version 3.14.1
Debian Jessie

Any ideas why this is happening, or how I can go about debugging it?

**Comment by wilfm** [comment]
Should be fixed with update - works happily with 3.14 in Fedora anyway
