### ISSUE TITLE
Black bar on top

### ISSUE THREAD

**Issue by tthanh** [wilfm/GnomeExtensionMaximusTwo#18]
When i turn off one extension, it appear. I need switch tab to other windows, and switch back, black bar disappear.
I'm using Fedora 21, gnome 3.14.2
![screenshot from 2015-01-26 04 02 32](https://cloud.githubusercontent.com/assets/8962973/5893278/3e17c166-a510-11e4-9ae0-f848d7a84ed3.png)

**Comment by MingcongBai** [comment]
Same thing has happened to Firefox, except that I can see the top panel. Firefox still has its window decoration taking place, but it's black.

**Comment by LeOSW42** [comment]
Same problem here, even when all other extensions are disabled.

**Comment by elmeunick9** [comment]
Same here

**Comment by DoctorJellyface** [comment]
Same here, happens when I open a maximised window. Extremely annoying.

**Comment by wilfm** [comment]
Same issue as in #12

**Comment by seveneves** [comment]
Same issue on OpenSuse 3.12 and Gnome 3.14.2. The black bar appears after Gnome locks the desktop after inactivity. The bar disappears after minimizing and maximizing a window. All widows are effected.

**Comment by tekstryder** [comment]
Confirmed on Arch Linux, Gnome 3.14.x. Seeing the additional black bar on top of various application windows. Also exhibits this behavior for existing windows on resume from suspend to ram.

**Comment by nommer** [comment]
Still occurs in Arch Gnome 3.16.1, **but** disappears when I minimize the offending maximized window and re-maximize it (i.e., whenever I see the black bar, press Super+Down then Super+Up). 

So the solution is clearly to somehow embed that workaround in the extension. :smile:

**Comment by wilfm** [comment]
Dupe of #12 - all should be fixed for now.
