### ISSUE TITLE
Gnome 3.16 support

### ISSUE THREAD

**Issue by wilfm** [wilfm/GnomeExtensionMaximusTwo#21]
Gnome 3.16 [has been released](https://mail.gnome.org/archives/gnome-announce-list/2015-March/msg00071.html)

Mainstream support is currently not quite available (except on Arch),a Ubuntu PPA's on the development version need to be used, & for Fedora you need the 22 Alpha (or possibly backports to older versions).

If you are using 3.16 and want, add 3.16 to the metadata.json file (similar to the method [here](https://github.com/wilfm/GnomeExtensionMaximusTwo/commit/bcacf38675f62fa4a1dbf8770f4403d7686d65f5)) and place the extension's files in `~/.local/share/gnome-shell/extensions/maximus-two@wilfinitlike.gmail.com`. I will submit a update at a future date after testing it and attempting to fix existing issues.

**Comment by ronjouch** [comment]
@wilfm 3.16 was pushed today to Arch. Patched my `metadata.json` and Maximus Two seemed happy. https://github.com/wilfm/GnomeExtensionMaximusTwo/issues/2 is still present, apart from that everything is fine like under 3.14 :)

**Comment by KingYes** [comment]
I just added this in my Arch, and I don't see that exts in Tweak tool.

**Comment by ronjouch** [comment]
@KingYes can you check (user-local) `~/.local/share/gnome-shell/extensions` and (system-global) `/usr/share/gnome-shell/extensions/` and check that the extension is in one of them ? In the extension folder, check `metadata.json` and ensure `"shell-version"` contains `"3.16"`. Then restart the shell (`Alt + F2`, `r`) and relaunch Tweak Tool.

If still problematic, please post a new issue with as much detail as possible. This issue is about supporting 3.16; if you were hit by the issue you'd see the extension in Tweak Tool, but it would be greyed out.

**Comment by KingYes** [comment]
Hi !
After reboot and reboot I see this now. Thanks. :)

**Comment by kaptoxic** [comment]
Can you update the extension on https://extensions.gnome.org/extension/844/maximus-two/?

**Comment by mat-mo** [comment]
I see in my journal:

gnome-session[704]: (gnome-shell:6393): Gjs-WARNING **: JS ERROR: TypeError: appMenu._label.setText is not a function
gnome-session[704]: updateAppMenu@/home/matanya/.local/share/gnome-shell/extensions/maximus-two@wilfinitlike.gmail.com/app_menu.js:41

**Comment by kaptoxic** [comment]
Extension seems to be working as usual, after modifying metadata.json

I see the error @mat-mo reported and I also see an additional one:
```
gnome-session[1445]: (gnome-shell:1511): Gjs-WARNING **: JS ERROR: TypeError: Shell.StageInputMode is undefined
gnome-session[1445]: onFocusChange@/home/ivcha/.local/share/gnome-shell/extensions/maximus-two@wilfinitlike.gmail.com/app_menu.js:74
```

**Comment by sheldonh** [comment]
Thanks, @ptpt. Your PR works perfectly on Fedora 22.

**Comment by davidcortesortuno** [comment]
I think it is not working for Gnome 3.16.2

**Comment by wilfm** [comment]
Should be fixed with https://github.com/wilfm/GnomeExtensionMaximusTwo/releases/tag/5

**Comment by ronjouch** [comment]
Hi @wilfm, thanks. Looks like v5 reuses code from PixelSaver, what should we expect with this? Specific areas needing testing?

**Comment by wilfm** [comment]
@ronjouch This extension is (currently, and in the past, and for quite a bit into the future) is almost entirely based on Pixel Saver, it started as I wanted to use the [Window Buttons](https://extensions.gnome.org/extension/426/window-buttons/) extension(s), which I then shared so others could use it. I think I will however add some features in (preferences, window menu, stuff) so it easy to use :)
