### ISSUE TITLE
gnome-shell stays at ~20% CPU when using Maximus Two

### ISSUE THREAD

**Issue by xHN35RQ** [wilfm/GnomeExtensionMaximusTwo#32]
For some reason Version 4 of this extension is causing `gnome-shell` to run at a consistent 20-25% CPU. I've noticed similar complaints on Pixels Saver extension, so perhaps it's some shared code between the two extensions.

I've not seen any problems with Version 2 of Maximus Two, so the CPU eating bugs were introduced in Version 3 or 4.

**Comment by wilfm** [comment]
Which OS and version of Gnome shell are you using?

**Comment by lbrfabio** [comment]
I have a similar problem. After a while gnome-shell run at ~95% CPU. 
This happened even after I disabled all the extensions except Maximus Two,

**Comment by xHN35RQ** [comment]
Ubuntu 15.04 Gnome 3.14

**Comment by Talv** [comment]
Same problem. MaximusTwo causes gnome-shell to eat 100% of the CPU core after certain time of activity.

```
$ gnome-shell --version
GNOME Shell 3.16.3

$ gsettings get org.gnome.shell enabled-extensions | sed 's/,/,\n/g'
['activities-config@nls1729',
 'multi-monitors-add-on@spin83',
 'apps-menu@gnome-shell-extensions.gcampax.github.com',
 'cpupower@mko-sl.de',
 'dash-to-dock@micxgx.gmail.com',
 'freon@UshakovVasilii_Github.yahoo.com',
 'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
 'native-window-placement@gnome-shell-extensions.gcampax.github.com',
 'middleclickclose@paolo.tranquilli.gmail.com',
 'openweather-extension@jenslody.de',
 'places-menu@gnome-shell-extensions.gcampax.github.com',
 'drive-menu@gnome-shell-extensions.gcampax.github.com',
 'steal-my-focus@kagesenshi.org',
 'topIcons@adel.gadllah@gmail.com',
 'user-theme@gnome-shell-extensions.gcampax.github.com',
 'wintitle@megh',
 'workspace-indicator@gnome-shell-extensions.gcampax.github.com',
 'gTile@vibou',
 'system-monitor@paradoxxx.zero.gmail.com',
 'tracker-search-provider@sinnix.de',
 'shell-volume-mixer@derhofbauer.at',
 'hibernate-status@dromi',
 'Recents@leonardo.bartoli.gmail.com',
 'caffeine@patapon.info',
 'windowoverlay-icons@sustmidown.centrum.cz',
 'notifications-alert-on-user-menu@hackedbellini.gmail.com',
 'clipboard-indicator@tudmotu.com',
 'all-windows@ezix.org',
 'maximus-two@wilfinitlike.gmail.com',
 'StatusTitleBar@devpower.org']
```

It appears that log has some hints about it:
http://pastebin.com/XHGNwyii

**Comment by ghost** [comment]
I've downgraded to [v2 of the extension](https://github.com/wilfm/GnomeExtensionMaximusTwo/releases/tag/2) and have no trouble with CPU craziness.

#33 seems to have fixed this bug for me on 3.14

**Comment by zakkak** [comment]
I also observe 95-100% CPU usage after some period.

ArchLinux 64bit
Gnome 3.18

**Comment by ghost** [comment]
@zakkak try [this branch](https://github.com/danielkza/GnomeExtensionMaximusTwo/) which has a fix (#33) for the problem. Use it until @wilfm can merge in the fix from @danielkza - it should eliminate the high CPU usage.

**Comment by doublerebel** [comment]
+1, patch seems to be working for me.  (protip, I used the patch version of the PR https://github.com/danielkza/GnomeExtensionMaximusTwo/commit/4c716528693e03574151fd61e7fb8d085e5b69ca.patch instead of having to clone the repo.)

**Comment by zakkak** [comment]
Patch works fine for me as well. 

@xHN35RQ thanks for pointing out.

**Comment by ghost** [comment]
I'm closing this since I've found a solution, and @danielkza has a pull request with the fix so once that pull request is merged everything will be good.
