### ISSUE TITLE
My Fedora Freeze because of the extension.

### ISSUE THREAD

**Issue by HankelBao** [wilfm/GnomeExtensionMaximusTwo#56]
I’m using Fedora 25 and after installing the extension, my operation system simply FREEZED!!
No operation works and even I CANNOT enter any other tty after reboot.
No error info in the only tty. The last info in the only ttf is “Started GNOME Display Manager. Dispatcher Service...t.-8ac8-4539-88f6-51cae1b087d6”
Can anyone help me since I REALLY don’t want to reinstall my os again?

**Comment by HankelBao** [comment]
I wait for about 5 minutes and somehow I can use other tty again.
I tried to simply delete extension from .local/share/gnome-shell/extensions but still didn’t work.
What else can I do to save my os?

**Comment by zer09** [comment]
@HankelBao did you solve your problem? I also experiencing this.

**Comment by HankelBao** [comment]
I was exhausted and  just ... reinstalled my operation system
