### ISSUE TITLE
Gnome-shell crash using MaximusTwo

### ISSUE THREAD

**Issue by damian-aragunde-udc** [wilfm/GnomeExtensionMaximusTwo#7]
Hi.
Setting up Empathy, I coud see that opening one friend's window chat, all gnome-shell crashes. Deactivating the MaximusTwo plugin solves the problem.
Curiosly, that only happends with this ONE friend on they 3 different account that he has: over Outlook, Hangouts and Facebook, and I could talk with the other friends without problem.
Analyzing it, the only difference maybe is that his name contains de 'ñ' character (and this is the name of the new window).
It's the first time that I opened that window and use Empathy [on this machine], so the window is not maximize and the size and positions was the standard.

Analyzing the 5 differents logs that I had, I notice that messages from Maximus Two appeared after the crash, so a try to deactivate Maximus Two and that works.

PS: I post that crash here because Maximus Two is the direct responsible of that, but this could be a gnome-shell related bug.
PS2: Searching on Google I couldn't find something useful about the GTK Critical errors that I could see.

**Comment by wilfm** [comment]
May have been fixed with version using update from Pixel Saver (https://github.com/deadalnix/pixel-saver/issues/14), you can get it here: https://github.com/wilfm/GnomeExtensionMaximusTwo/releases/tag/4

**Comment by damian-aragunde-udc** [comment]
Sorry for that late response. In that moment I saw the answer and examined it, but because I couldn't try if it was fixed, I forgot to post again.

Now trying out with Empathy 3.12.11 over Gnome 3.18.3. Because Gnome 3.18 it's not officially supported, I have cloned the master branch from GitHub and I edited the metadata file (adding 3.18).

My problem seems solved. MaximusTwo seems working fine on my 3.18. Thanks a lot for the support. You can mark it as solved.
